create database IF NOT EXISTS CEMS;
use CEMS;

drop table IF EXISTS FRAGMENTS;
drop table IF EXISTS METABOLITES;

create table METABOLITES (
	ID INT auto_increment,
    COMPOUND_NAME VARCHAR (255) NOT NULL,
    FORMULA VARCHAR (255) NOT NULL,
    MONOISOTOPIC_MASS DOUBLE NOT NULL,
    M_Z DOUBLE NOT NULL,
    MT_COMPND DOUBLE,
    MT_METS DOUBLE,
    RMT_METS DOUBLE,
    MT_MES DOUBLE,
    RMT_MES DOUBLE,
    PRIMARY KEY (ID)
);

create table FRAGMENTS (
	ID INT auto_increment,
    ID_MET INT,
    M_Z DOUBLE NOT NULL,
    INTENSITY DOUBLE,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_MET) REFERENCES METABOLITES(ID)
);


